db_config_source.user=CASPIEOWN
db_config_source.password=CASPIEOWN
db_config_source.host=192.168.80.19
db_config_source.database=MYSASTEST
db_config_source.allow_local_infile=true

#MYSQL db
db_config_target.user=root
db_config_target.password=root
db_config_target.host=192.168.80.53:3306
db_config_target.database=sas_db
db_config_target.allow_local_infile=true


data_dir=C:\\SAS\\dbMigration\\src\\main\\resources\\csv
max_workers=16